In [5]:
# 必要な場合
# !pip install chromedriver-binary==87.0.4280.88.0

In [14]:
import time
from bs4 import BeautifulSoup
import pandas as pd

In [1]:
import sys
sys.path.append('modules')

# 前処理
from MakeDatabase import MakeDatabase
from MakeDatabase import Return

# スクレイピング
from ScrapeLib import ScrapeTable
from ScrapeLib import ScrapePostRace
from ScrapeLib import ScrapeTodayRace

## テスト用

In [30]:
lid ='masami.20170621@gmail.com'
pwsd ='masami1127'

st = ScrapeTable(horse=True, peds=False, horse_df_ids=[1,3])
# driver = st.open_driver(headless=False)
# driver = st.driver_with_login(lid, pwsd, headless=False)

# horse_id = '2012100940'
# url = 'https://db.netkeiba.com/horse/' + str(horse_id)
# url = 'https://db.netkeiba.com/?pid=horse_training&id=' + str(2015104961)

race_id = 202006050108
url = 'https://db.netkeiba.com/race/' + str(race_id)
spr = ScrapePostRace(shutuba=True)
# driver = spr.open_driver(headless=False)
driver = spr.driver_with_login(lid, pwsd, headless=False)

driver.get(url)
time.sleep(2)
content = driver.page_source.encode('utf-8')
soup = BeautifulSoup(content, "html.parser")
data = pd.read_html(str(soup))

ログイン完了

In [28]:
data[5]

IndexError: list index out of range

## 競走馬基本情報,過去レース取得，競走馬血統，調教

In [40]:
lid ='masami.20170621@gmail.com'
pwsd ='masami1127'

# st = ScrapeTable(horse=True, peds=True, train=True)
st = ScrapeTable(train=True)

# driver = st.open_driver(headless=False)
driver = st.driver_with_login(lid, pwsd, headless=False)

ログイン完了

In [41]:
cf = CommonFunction()
horse_id_list = cf.list_from_csv('Data/horse_ids.csv')
horse_id_list[0] = horse_id_list[0][-10:]

In [42]:
# horse_id_list = ['2013102966', '2013101519', '2012109053']
horse_id_list = horse_id_list[0:50]
error_file = 'Data/error_test.csv'

# scrape_horse = st.scrape_horse(driver, horse_id_list, error_file)
# st.scrape_peds(driver, horse_id_list, error_file)
scrape_train = st.scrape_train(driver, horse_id_list, error_file)

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [02:32<00:00,  3.05s/it]

In [43]:
driver.quit()

In [45]:
# st.df_concat_horse(scrape_horse)
st.df_concat_train(scrape_train)

In [32]:
st.horse_info_df.head(2)

,Name,0,1,2,3,4,5,6,7,8,9,TrainerID,OwnerID,BreederID
2013102966,マカーオーン,生年月日,調教師,馬主,生産者,産地,セリ取引価格,獲得賞金,通算成績,主な勝鞍,近親馬,00392,216033,230047
2013102966,マカーオーン,2013年4月13日,古賀史生 (美浦),伊丹彰,鮫川啓一,浦河町,-,670万円 (中央),18戦1勝 [1-0-0-17],15'2歳未勝利,ソラニー、マースストロング,00392,216033,230047

In [33]:
st.past_race_df.head(2)

,日付,開催,天気,R,レース名,映像,頭数,枠番,馬番,オッズ,...,通過,ペース,上り,馬体重,厩舎ｺﾒﾝﾄ,備考,勝ち馬(2着馬),賞金,RaceID,JockeyID
2013102966,2017/01/26,大井,晴,10,白富士特別競走,NaN,16,8,15,101.9,...,16-16-16-16,37.8-41.0,42.0,460(-7),NaN,NaN,ケイズイーグル,NaN,201744012610,a012b
2013102966,2017/01/12,船橋,晴,9,C1二,NaN,9,8,8,116.1,...,8-8-8-8,40.8-38.5,41.3,467(-15),NaN,NaN,ハクサンワールド,NaN,201743011209,05409

In [34]:
st.peds_df.head(2)

,0,1,2,3,4,5,6,7,8,9,...,53,54,55,56,57,58,59,60,61,62
0,2013102966,2002100996,000a00033a,000a0012bf,000a000f2b,000a001042,000a0078a6,000a007459,000a0013f0,000a0072a0,...,000a006dcd,000a00104e,000a007f95,1955108565,000a000297,000a000e1f,000a007704,1959100632,000a0008af,000a002b3c
1,2013101519,2005102216,1998101516,000a00033a,000a0012bf,000a000f2b,000a007459,000a008c1e,000a0019b6,000a008c1d,...,000a008e05,000a000ded,000a008e04,000a00019b,000a000efe,000a000e46,000a007535,000a009615,000a000e03,000a006d05

In [46]:
st.train_df.head(2)

,日付,コース,馬場,乗り役,調教タイム,位置,脚色,評価,評価.1,映像,RaceID
2017105829,2020/11/18(水),美坂,良,助手,-li53.4li39.4li26.0li13.1li 内ｱｳｽﾄﾞﾙｯｸ強めと併せで併入,2.0,馬也,まずまず,C,NaN,202005050507
2017105829,2020/11/04(水),美坂,稍,助手,-li54.2li40.0li26.2li13.0li,NaN,馬也,目立たず,C,NaN,202005050207

In [24]:
st.df_to_csv_horse_peds('Data', -1)

## 出馬表（結果データベース）スクレイピング

In [ ]:
lid ='masami.20170621@gmail.com'
pwsd ='masami1127'

# レースID作成
race_id_list1 = []
race_id_list = [ '0605', '0906', '0703' ]
for race_id in race_id_list:
    for j in range(1, 3):
        for i in range(7, 13):
            race_id_list1 += [ '2020' + race_id + str(j).zfill(2) + str(i).zfill(2) ]
race_id_list1 = race_id_list1[:10]

spr = ScrapePostRace(horse=True, peds=True, shutuba=True, train=True)
driver = spr.open_driver(headless=False)
# driver = spr.driver_with_login(lid, pwsd, headless=False)
error_file = 'Data/error_test.csv'

scrape_data = spr.scrape_shutuba(driver, race_id_list1, error_file)

In [ ]:
spr.df_concat_shutuba(scrape_data)

In [ ]:
spr.shutuba_df.head(2)

In [13]:
spr.payouts_df.head(2)

    0        1              2        3
0  単勝        3            310        1
1  複勝  3br5br2  110br120br110  1br3br2

In [14]:
spr.corner_rank_df.head(2)

                  0                            1
202005050107  3コーナー  (*2,3)-(8,10)=9,6(7,5)(4,1)
202005050107  4コーナー    (*2,3)(8,10)=9(6,5)-1-7,4

In [15]:
spr.lap_time_df.head(2)

                0                                                  1
202005050107  ラップ  13.0 - 11.7 - 11.7 - 11.8 - 12.1 - 11.5 - 11.5...
202005050107  ペース  13.0 - 24.7 - 36.4 - 48.2 - 60.3 - 71.8 - 83.3...

In [16]:
# 保存
spr.df_to_csv_all('Data', '100')

In [17]:
driver.quit()

## 当日データスクレイピング

In [19]:
st = ScrapeTodayRace(today_race=True, horse=True, peds=True)
driver = st.open_driver(headless=False)

race_id_list = [202005040811, 202009030811]

scrape_data = st.scrape_today(driver, race_id_list)

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:15<00:00,  7.62s/it]

In [89]:
st.df_concat_today(scrape_data)

In [90]:
st.today_race_df.head(2)

,枠,馬番,印,馬名,性齢,斤量,騎手,厩舎,馬体重(増減),オッズ,...,JockeyID,Year,Date,Number,Location,Term,Day,R,Racetype_Length,Condition
,枠,馬番,印,馬名,性齢,斤量,騎手,厩舎,馬体重(増減),オッズ,...,,,,,,,,,,
202005040811,1,1,--,ブラストワンピース,牡5,58.0,池添,美浦大竹,550(+8),32.3,...,01032,2020,2020/11/14,12,東京,04,08,11,芝2000m,良
202005040811,2,2,--,カデナ,牡6,58.0,田辺,栗東中竹,478(+2),146.1,...,01075,2020,2020/11/14,12,東京,04,08,11,芝2000m,良

In [13]:
# 欠落する競走馬データ取得
horse_id_list = [2015104961, 2014101976]
horse_id_yet = st.find_horse_id_yet(horse_id_list)

peds_id_list = [2015104961]
error_file = 'Data/error_test.csv'
scrape_data = st.scrape_horse(driver, horse_id_yet, error_file)
st.scrape_peds(driver, horse_id_yet, peds_id_list, error_file)

In [92]:
st.df_concat_horse(scrape_data)

In [93]:
st.past_race_df.head(2)

,日付,開催,天気,R,レース名,映像,頭数,枠番,馬番,オッズ,...,着差,ﾀｲﾑ指数,通過,ペース,上り,馬体重,厩舎ｺﾒﾝﾄ,備考,勝ち馬(2着馬),賞金
2015104882,2020/11/01,4東京8,曇,11.0,天皇賞(秋)(G1),NaN,12,1.0,1,32.3,...,1.7,**,8-5-6,36.5-33.6,34.6,550(+8),NaN,NaN,アーモンドアイ,NaN
2015104882,2020/06/28,3阪神8,曇,11.0,宝塚記念(G1),NaN,18,8.0,18,9.9,...,4.5,**,5-6-5-10,34.6-36.3,40.3,542(0),NaN,NaN,クロノジェネシス,NaN

In [94]:
st.horse_info_df.head(2)

,Name,0,1,2,3,4,5,6,7,8,9,10
2015104882,ブラストワンピース,生年月日,調教師,馬主,募集情報,生産者,産地,セリ取引価格,獲得賞金,通算成績,主な勝鞍,近親馬
2015104882,ブラストワンピース,2015年4月2日,大竹正博 (美浦),シルクレーシング,1口:4万円/500口,ノーザンファーム,安平町,-,"5億7,235万円 (中央)",15戦7勝 [7-0-0-8],18'有馬記念(G1),ホウオウピースフル、ヴィクトリアピース

In [95]:
st.peds_df.head(2)

,0,1,2,3,4,5,6,7,8,9,...,53,54,55,56,57,58,59,60,61,62
0,2015104882,000a011996,000a010a5f,000a0000d1,000a0000d3,000a000e04,000a000491,000a009233,000a000628,000a00922b,...,000a00021e,000a000e44,000a008e24,000a0064f2,000a0019da,000a000e04,000a008298,000a009c97,000a001220,000a009c96
1,2014104449,2002100816,000a00033a,000a0012bf,000a000f2b,000a001042,000a0078a6,000a007459,000a0013f0,000a0072a0,...,000a008080,000a00110c,000a008081,000a00feda,000a0001ff,000a00117c,000a00725c,000a00868f,000a000253,000a00868e

In [96]:
driver.quit()